webtalk_init -webtalk_dir C:/Users/subha/Desktop/Subhash/Verilog/RISC-V_PIPELINE/RISC-V_PIPELINE.sim/sim_1/behav/xsim/xsim.dir/Final_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri May  1 21:39:57 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2729669" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211882105_0_0_763" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "8137b027-8afd-497b-ac75-62bfaf2c05ce" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "ae0e7f39c07d4f24be965ada2ba448d1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "42" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.37_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6200_KB" -context "xsim\\usage"
webtalk_transmit -clientid 66511224 -regid "211882105_0_0_763" -xml C:/Users/subha/Desktop/Subhash/Verilog/RISC-V_PIPELINE/RISC-V_PIPELINE.sim/sim_1/behav/xsim/xsim.dir/Final_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/subha/Desktop/Subhash/Verilog/RISC-V_PIPELINE/RISC-V_PIPELINE.sim/sim_1/behav/xsim/xsim.dir/Final_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/subha/Desktop/Subhash/Verilog/RISC-V_PIPELINE/RISC-V_PIPELINE.sim/sim_1/behav/xsim/xsim.dir/Final_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
